name: Publish

on:
  release:
    types: [published]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
  build-n-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [tests]
    env:
      name: pypi
      url: https://pypi.org/p/chainlit
    permissions:
      contents: read
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node.js 16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
          cache: "npm"
      - name: Install UI JS dependencies
        run: npm run installUiDeps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Copy readme to src
        run: cp README.md src/
      - name: Build chainlit
        run: npm run build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: src/dist
          password: ${{ secrets.PYPI_API_TOKEN }}
